CREATE TABLE imgs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    img_url TEXT NOT NULL,
    photographer TEXT NOT NULL,
    profile_url TEXT NOT NULL,
    download_location TEXT NOT NULL
);