CREATE TABLE posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    img_url TEXT NOT NULL,
    img_photographer TEXT NOT NULL,
    portfolio_url TEXT,
    img_dwn_link TEXT NOT NULL,
    img_alt TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES users(id) NOT NULL
);